### ISSUE TITLE
[bug] exoscale_compute name attribute not idempotent

### ISSUE THREAD

**Issue by mcanevet** [cab105/terraform-provider-exoscale#3]
Hello,

I started a VM with `terraform apply` setting the name to `mynode`. The name of the VM in exoscale portal is `mynode` but when I launch `terraform plan`, it wants to change the name of my node:

```
name:             "VM-<uuid>" => "mynode"
```

And if I do a `terraform apply` it says that it changed the name of my node, but `terraform plan` still reports the change from `VM-<uuid>` to `mynode`

**Comment by cab105** [comment]
I have resolved this under changeset: 4d1db93cb4905c9e5a1be91bc143b99f9fcd8113
