### ISSUE TITLE
[question] What about cloudstack_instance provider

### ISSUE THREAD

**Issue by mcanevet** [cab105/terraform-provider-exoscale#5]
Hello,

I'm curious to know why you develop an `exoscale_compute` provider while `cloudstack_instance` provider works quite well with exoscale.
I proposed 2 PR to add `security_group_names`[0] and `affinity_group_names`[1] support to the `cloudstack_instance` provider. And I think we can manage almost all the features of the `exoscale_compute` provider with the generic cloudstack provider.

[0] https://github.com/hashicorp/terraform/pull/7240
[1] https://github.com/hashicorp/terraform/pull/7242

**Comment by sebgoa** [comment]
@mcanevet thanks for the inquiry.

That's because this plugin also supports exoscale SOS and DNS services.
And we opted to use the exoscale go client (egoscale) instead of the generic cloudstack go client.
