### ISSUE TITLE
Readme - Security groups & egress/ingress rules

### ISSUE THREAD

**Issue by marcaurele** [cab105/terraform-provider-exoscale#7]
In the readme you're saying that there is no API call to fetch the ingress and egress rules, but there is one actually. You should use the listSecurityGroups API call and you will receive both set of rules:
https://cloudstack.apache.org/api/apidocs-4.4/user/listSecurityGroups.html

**Comment by cab105** [comment]
Thank you for bringing this to my attention.  I will update the plugin to account for this.

**Comment by cab105** [comment]
This has been resolved by commit: b6b0bdf52c47e642adc3cadd5d66f8818556e3fd
